export const ORDER_BOOK_UPDATES = {
  REFRESH: 'ORDER_BOOK_REFRESH',
  ADD_ORDER: 'ORDER_BOOK_ADD_ORDER',
  CHANGE_ORDER: 'ORDER_BOOK_CHANGE_ORDER',
  REMOVE_ORDER: 'ORDER_BOOK_REMOVE_ORDER',
};

export const ORDER_DEPTH_UPDATES = {
  REFRESH: 'REFRESH',
  ADD_ORDER: 'ADD_ORDER',
  CHANGE_ORDER: 'CHANGE_ORDER',
  REMOVE_ORDER: 'REMOVE_ORDER',
};

export const TRADE_HISTORY_UPDATES = {
  REFRESH: 'TRADE_HISTORY_REFRESH',
  ADD_TRADE: 'TRADE_HISTORY_ADD_TRADE',
};

export const SUBSCRIBE = {
  ORDER_BOOK: 'SUBSCRIBE_ORDER_BOOK',
  ORDER_DEPTH: 'SUBSCRIBE_ORDER_DEPTH',
  TRADE_HISTORY: 'SUBSCRIBE_TRADE_HISTORY',
};

export const CHANGE_ACCOUNT = 'CHANGE_ACCOUNT';
